name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
        if: matrix.os == 'ubuntu-latest'
      - run: |
          brew install boost
          echo "BOOST_ROOT=$(brew --prefix boost)" >> $GITHUB_ENV
        if: matrix.os == 'macos-latest'
      - name: Get version
        id: get_version
        run: echo "version=${{ github.run_number }}" >> "$GITHUB_OUTPUT"
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.os }}
          path: |
            ip_filter-*.deb
            ip_filter-*.tar.gz
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List downloaded files
        run: ls -R artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.version }}
          release_name: Release ${{ needs.build.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/ip_filter-0.0.${{ needs.build.outputs.version }}-Linux.deb
          asset_name: ip_filter-0.0.${{ needs.build.outputs.version }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/ip_filter-0.0.${{ needs.build.outputs.version }}-Darwin.tar.gz
          asset_name: ip_filter-0.0.${{ needs.build.outputs.version }}-Darwin.tar.gz
          asset_content_type: application/gzip
